# Generated by Django 5.2.7 on 2025-11-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account',
            field=models.CharField(blank=True, max_length=64, verbose_name='Bank account / IBAN'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bank name'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=64, verbose_name='BIC / SWIFT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_reg_number',
            field=models.CharField(blank=True, max_length=64, verbose_name='Company registration number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=200, verbose_name="Contact persons's email"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Responsible contact person'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name="Contact person's phone number"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_position',
            field=models.CharField(blank=True, max_length=128, verbose_name="Contact person's position"),
        ),
        migrations.AlterField(
            model_name='customer',
            name='delivery_address',
            field=models.TextField(blank=True, verbose_name='Default delivery address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='legal_name',
            field=models.CharField(max_length=255, verbose_name='Legal company name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registered_address',
            field=models.TextField(blank=True, verbose_name='Registered company address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tax ID (VAT number)'),
        ),
    ]
